import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/sections/Navbar";
import Footer from "@/sections/Footer";

export const metadata: Metadata = {
  title: "SmartEdge Consulting & Analytics - Data-driven Business Solutions",
  icons: {
    icon: "/favicon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased font-serif bg-pry/90`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
